server:
  port: 8088
  display-name: code-generator

#spring:
#  datasource:
#    url: jdbc:h2:file:~/.h2/mybatisplus-gen;MODE=MYSQL
#    driver-class-name: org.h2.Driver
#    username: root
#    password: root
#    schema: classpath:sql/schema.sql
#    data: classpath:sql/data.sql
#  h2:
#    console:
#      # http://ip:port/h2-console
#      enabled: true
#      settings:
#        web-allow-others: true

spring:
  datasource:
    name: dynamicSQL
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://115.220.10.37:3309/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: mybatisplus-generator-web
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    mode: LEGACYHTML5
    suffix: .html
logging:
  level:
    com.reapal: info
    com.com.baomidou: debug
